import type { User, Customer } from "@/types";

export const users: User[] = [
  {
    id: "admin-01",
    name: "Alexia Admin",
    email: "admin@lexora.net",
    role: "Admin",
    referrerId: null,
    totalIncome: 50000,
    avatar: "https://placehold.co/100x100.png",
    createdAt: "2023-01-10",
  },
  {
    id: "rd-01",
    name: "Rajan Director",
    email: "rajan.d@lexora.net",
    role: "Regional Director",
    referrerId: "admin-01",
    totalIncome: 45000,
    avatar: "https://placehold.co/100x100.png",
    createdAt: "2023-02-15",
  },
  {
    id: "hgm-01",
    name: "Harini Manager",
    email: "harini.m@lexora.net",
    role: "Head Group Manager",
    referrerId: "rd-01",
    totalIncome: 30000,
    avatar: "https://placehold.co/100x100.png",
    createdAt: "2023-03-20",
  },
  {
    id: "gom-01",
    name: "Gita Operator",
    email: "gita.o@lexora.net",
    role: "Group Operation Manager",
    referrerId: "hgm-01",
    totalIncome: 22000,
    avatar: "https://placehold.co/100x100.png",
    createdAt: "2023-04-01",
  },
  {
    id: "tom-01",
    name: "Tomesh Teamlead",
    email: "tomesh.t@lexora.net",
    role: "Team Operation Manager",
    referrerId: "gom-01",
    totalIncome: 18000,
    avatar: "https://placehold.co/100x100.png",
    createdAt: "2023-05-10",
  },
  {
    id: "sm-01",
    name: "Sunil Sales",
    email: "sunil.s@lexora.net",
    role: "Salesman",
    referrerId: "tom-01",
    totalIncome: 12500,
    avatar: "https://placehold.co/100x100.png",
    createdAt: "2023-06-01",
  },
  {
    id: "sm-02",
    name: "Sara Varma",
    email: "sara.v@lexora.net",
    role: "Salesman",
    referrerId: "tom-01",
    totalIncome: 9800,
    avatar: "https://placehold.co/100x100.png",
    createdAt: "2023-06-05",
  },
   {
    id: "tom-02",
    name: "Tanya Lead",
    email: "tanya.l@lexora.net",
    role: "Team Operation Manager",
    referrerId: "gom-01",
    totalIncome: 16500,
    avatar: "https://placehold.co/100x100.png",
    createdAt: "2023-05-12",
  },
  {
    id: "sm-03",
    name: "Samir Patel",
    email: "samir.p@lexora.net",
    role: "Salesman",
    referrerId: "tom-02",
    totalIncome: 11200,
    avatar: "https://placehold.co/100x100.png",
    createdAt: "2023-06-02",
  },
];

export const customers: Customer[] = [
  {
    id: "cust-001",
    name: "Rohan Industries",
    contactInfo: "rohan@industries.com",
    address: "123 Business Bay, Colombo",
    tokenSerial: "LX2000-A1B2",
    salesmanId: "sm-01",
    saleDate: "2023-08-15",
    commissionDistributed: true,
  },
  {
    id: "cust-002",
    name: "Priya Creations",
    contactInfo: "priya@creations.co",
    address: "456 Art Street, Kandy",
    tokenSerial: "LX2000-C3D4",
    salesmanId: "sm-01",
    saleDate: "2023-08-20",
    commissionDistributed: true,
  },
  {
    id: "cust-003",
    name: "Kavita Solutions",
    contactInfo: "kavita@solutions.lk",
    address: "789 Tech Park, Galle",
    tokenSerial: "LX2000-E5F6",
    salesmanId: "sm-02",
    saleDate: "2023-09-01",
    commissionDistributed: true,
  },
   {
    id: "cust-004",
    name: "Dinesh Exports",
    contactInfo: "dinesh@exports.com",
    address: "321 Trade Center, Colombo",
    tokenSerial: "LX2000-G7H8",
    salesmanId: "sm-03",
    saleDate: "2023-09-05",
    commissionDistributed: true,
  },
  {
    id: "cust-005",
    name: "Anjali Imports",
    contactInfo: "anjali@imports.lk",
    address: "654 Commerce Plaza, Jaffna",
    tokenSerial: "LX2000-I9J0",
    salesmanId: "sm-03",
    saleDate: "2023-09-10",
    commissionDistributed: false,
  },
];
