"use client";

import React from "react";
import { User } from "@/types";
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from "@/components/ui/card";
import { DollarSign, Users, Activity } from "lucide-react";
import { getDownlineIdsAndUsers } from "@/lib/hierarchy";
import { Bar, BarChart, ResponsiveContainer, XAxis, YAxis } from "recharts";
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import { useIsMobile } from "@/hooks/use-mobile";

interface ManagerDashboardProps {
  user: User;
  allUsers: User[];
}

const ManagerDashboard: React.FC<ManagerDashboardProps> = ({ user, allUsers }) => {
  const isMobile = useIsMobile();
  const { users: downlineUsers } = getDownlineIdsAndUsers(user.id, allUsers);
  const teamIncome = downlineUsers.reduce((acc, u) => acc + u.totalIncome, 0);

  const chartData = downlineUsers
    .sort((a,b) => b.totalIncome - a.totalIncome)
    .slice(0, 5)
    .map(u => ({
    name: u.name.split(' ')[0],
    income: u.totalIncome,
  }));

  const chartConfig = {
    income: {
      label: "Income (LKR)",
      color: "hsl(var(--primary))",
    },
  };

  return (
    <div className="flex flex-col gap-6">
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Personal Income</CardTitle>
            <DollarSign className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">LKR {user.totalIncome.toLocaleString()}</div>
            <p className="text-xs text-muted-foreground">Your total accumulated commission</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Team Income</CardTitle>
            <Users className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">LKR {teamIncome.toLocaleString()}</div>
            <p className="text-xs text-muted-foreground">Total from your downline</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Team Size</CardTitle>
            <Activity className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">+{downlineUsers.length} Members</div>
            <p className="text-xs text-muted-foreground">Direct and indirect reports</p>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Top Team Performers</CardTitle>
          <CardDescription>Income generated by your top 5 team members.</CardDescription>
        </CardHeader>
        <CardContent className="pl-2">
          <ChartContainer config={chartConfig} className="h-[300px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={chartData} accessibilityLayer margin={{ top: 5, right: 20, left: isMobile ? -10 : 10, bottom: 5 }}>
                <XAxis
                  dataKey="name"
                  stroke="#888888"
                  fontSize={12}
                  tickLine={false}
                  axisLine={false}
                />
                <YAxis
                  stroke="#888888"
                  fontSize={12}
                  tickLine={false}
                  axisLine={false}
                  tickFormatter={(value) => `LKR ${value / 1000}k`}
                />
                  <ChartTooltip
                  cursor={false}
                  content={<ChartTooltipContent indicator="dot" />}
                />
                <Bar dataKey="income" fill="hsl(var(--primary))" radius={[4, 4, 0, 0]} maxBarSize={isMobile ? 30 : undefined} />
              </BarChart>
            </ResponsiveContainer>
          </ChartContainer>
        </CardContent>
      </Card>
    </div>
  );
};

export default ManagerDashboard;
